### ISSUE TITLE
async after-the-request action

### ISSUE THREAD

**Issue by christopher5106** [benglard/waffle#14]
Hi,

How would you perform an action at each request, that does not delay rendering the answer to the request ?

Thanks

**Comment by benglard** [comment]
I'm assuming this is a blocking task, since otherwise you could safely put them both in the route handler. This is not currently easily possible. You could try running the task on a separate thread pool using the torch threads package. [Here](https://github.com/alexander-beer-weiss/multi-GPU_server) is an example of waffle + threads. Or write some simple code in waffle/app.lua to keep a table of post-request functions and run them and I'd happily accept a pull request! (I likely wont have time to do this myself for a while but can try)

**Comment by christopher5106** [comment]
What would be great, do you think it is possible to create a function to release the hand and render the results, so that some code can continue to be executed behind the statement ?

**Comment by benglard** [comment]
No reason you cant have code execute after res.send

**Comment by christopher5106** [comment]
That's super great. So you have your after-request process. Thanks!
